"""LLMs.txt generation — scan a website and produce an llms.txt file.

The llms.txt format follows Matt Webb's spec (https://llmstxt.org/):
a markdown file at the site root that helps LLMs discover and prioritize
the site's key pages.
"""

import logging
from urllib.parse import urljoin, urlparse

import httpx
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)


async def discover_pages(url: str, max_pages: int = 50) -> list[str]:
    """Discover page URLs on a site by fetching the homepage and finding same-domain links."""
    parsed = urlparse(url)
    base_domain = parsed.netloc
    base_url = f"{parsed.scheme}://{parsed.netloc}"

    discovered: list[str] = []
    seen = set()

    try:
        async with httpx.AsyncClient(follow_redirects=True, timeout=15) as client:
            resp = await client.get(url)
            if resp.status_code != 200:
                logger.warning("Failed to fetch %s: %d", url, resp.status_code)
                return [url]  # fallback: just return the input URL

            soup = BeautifulSoup(resp.text, "html.parser")
            for a in soup.find_all("a", href=True):
                href = a["href"].strip()
                full_url = urljoin(base_url, href)
                full_parsed = urlparse(full_url)

                # Skip external links, anchors, mailto, etc.
                if full_parsed.netloc and full_parsed.netloc != base_domain:
                    continue
                if not full_parsed.scheme.startswith("http"):
                    continue
                if full_url in seen:
                    continue

                seen.add(full_url)
                discovered.append(full_url)

                if len(discovered) >= max_pages:
                    break

    except Exception as e:
        logger.warning("Page discovery failed for %s: %s", url, e)
        return [url]

    if not discovered:
        discovered = [url]

    return discovered


async def extract_title_and_description(page_url: str, scraper_url: str) -> tuple[str, str]:
    """Extract the title and a short description from a page."""
    title = ""
    description = ""
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(f"{scraper_url}/scrape", json={"url": page_url})
            if resp.status_code == 200:
                body = resp.json()
                if body.get("success"):
                    md = body.get("data", {}).get("markdown", "")
                    source = body.get("data", {}).get("source", "")

                    # If we got llms.txt directly, extract just the title
                    if source == "llms.txt":
                        lines = md.strip().split("\n")
                        for line in lines:
                            if line.startswith("# ") and not line.startswith("## "):
                                title = line[2:].strip()
                                break

                    # Extract title from first heading in markdown
                    if not title:
                        for line in md.split("\n"):
                            line = line.strip()
                            if line.startswith("# ") and not line.startswith("## "):
                                title = line[2:].strip()
                                break

                    # Extract description: first non-heading paragraph, first 150 chars
                    for line in md.split("\n"):
                        stripped = line.strip()
                        if stripped and not stripped.startswith("#") and not stripped.startswith("!") and not stripped.startswith("["):
                            description = stripped[:150].strip()
                            break
    except Exception as e:
        logger.warning("Failed to scrape %s: %s", page_url, e)

    return title or page_url.rstrip("/").split("/")[-1].replace("-", " ").title(), description


def generate_llms_txt(site_url: str, pages: list[dict]) -> str:
    """Compile discovered page info into the llms.txt format."""
    parsed = urlparse(site_url)
    site_name = parsed.netloc

    lines = [f"# {site_name}"]
    lines.append("")
    lines.append(f"> Auto-generated by GroktoCrawl. This file helps AI agents discover and prioritize content on {site_url}.")
    lines.append("")

    for i, page in enumerate(pages):
        title = page.get("title", "")
        url = page.get("url", "")
        desc = page.get("description", "")

        if desc:
            lines.append(f"- [{title}]({url}): {desc}")
        else:
            lines.append(f"- [{title}]({url})")

    lines.append("")
    lines.append("---")
    lines.append(f"> This llms.txt was auto-generated by [GroktoCrawl](https://github.com/groktopus/groktocrawl) on {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}.")

    return "\n".join(lines)


async def generate_llmstxt(
    url: str,
    max_pages: int = 50,
    scraper_url: str = "http://scraper-svc:8001",
) -> dict:
    """Full pipeline: discover → scrape → compile.

    Returns dict with keys: llms_txt (str), url (str), pages_discovered (int), pages_summarized (int)
    """
    discovered_urls = await discover_pages(url, max_pages)
    logger.info("Discovered %d pages from %s", len(discovered_urls), url)

    pages = []
    for page_url in discovered_urls[:max_pages]:
        title, description = await extract_title_and_description(page_url, scraper_url)
        pages.append({"url": page_url, "title": title, "description": description})

    llms_content = generate_llms_txt(url, pages)

    return {
        "llms_txt": llms_content,
        "url": url,
        "pages_discovered": len(discovered_urls),
        "pages_summarized": len(pages),
    }
